version: '3.2'

services:
  master:
    image: tudo/clos-ssd:master
    hostname: "master"
    container_name: "master"
    ports:
      - "50070:50070"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
  slave1:
    image: tudo/clos-ssd:slave
    hostname: "slave1"
    container_name: "slave1"
    ports:
      - "50075:50075"
      - "8042:8042"
  slave2:
    image: tudo/clos-ssd:slave-nodata
    hostname: "slave2"
    container_name: "slave2"
    ports:
      - "50076:50075"
      - "8043:8042"
